### ISSUE TITLE
evok web client: settings menu not working

### ISSUE THREAD

**Issue by noreway** [UniPiTechnology/evok#25]
**Environment**
- UniPi Neuron M503
- Jessie Lite
- evok (master branch)
- accessing web client with Chrome 59

**Error**
- 404 during page load: http://192.168.20.23/js/jquery/jquery.tmpl.js
- click on settings menu item resulting in a javascript error:
```
Uncaught TypeError: $(...).tmpl is not a function
    at HTMLDivElement.<anonymous> (http://192.168.20.23/:44:33)
    at HTMLDocument.dispatch (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:1043:238)
    at HTMLDocument.r.handle (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:1010:90)
    at Object.trigger (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:1033:169)
    at HTMLDivElement.<anonymous> (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:1134:21)
    at Function.each (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:72:41)
    at n.fn.init.each (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:21:18)
    at n.fn.init.trigger (http://192.168.20.23/js/jquery/jquery-2.1.1.min.js:1133:21)
    at a.(anonymous function).(anonymous function)._trigger (http://192.168.20.23/js/jquery/jquery.mobile-1.4.5.min.js:298:33)
    at a.(anonymous function).(anonymous function)._createWidget (http://192.168.20.23/js/jquery/jquery.mobile-1.4.5.min.js:236:184)
```

**Comment by tknot** [comment]
The Settings menu is unfortunately purely a development concept. The Master branch has always been meant more for development (with the GUI itself serving as an example for using the API), and carries a risk of coming across features which are not yet fully implemented. It is true that with the release of Neuron it also temporarily (and rather unfortunately) became the only point for obtaining EVOK compatible with Neuron. We have decided to create an internal development repository to prevent these problems in the future.

With this in mind I have removed the broken elements from the GUI page.

As for the issue regarding the JQuery 404, it should now be fixed, as per https://github.com/UniPiTechnology/evok/pull/21

Apologies for any inconvenience
